services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    volumes:
      - ./src/test/etc/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "1883:1883"
      - "61613:61613"
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "16379:6379"
  mailpit:
    image: axllent/mailpit:v1.20.5
    ports:
      - "1025:1025"
      - "8025:8025"
  kafka:
    image: apache/kafka-native:latest
    ports:
      - "9092:9092"
      - "9093:9093"
  sshd-test:
    image: linuxchina/sshd-test:latest
    ports:
      - "2022:22"